### ISSUE TITLE
Globals definition for Browser, Node...

### ISSUE THREAD

**Issue by davidurco** [nuxt/eslint#354]
### Describe the feature

Default config should include globals for browser, node etc to avoid errors like `ESLint: 'setTimeout' is not defined.(no-undef). ` or `ESLint: 'process' is not defined.(no-undef)`

### Additional information

- [X] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/eslint/discussions) and [issues](https://github.com/nuxt/eslint/issues).

**Comment by jeannen** [comment]
Same issue here, when I use console.log and other browser-related globals I get `'console' is not defined.eslint[no-undef](https://eslint.org/docs/latest/rules/no-undef)`

Managed to fix it using this config:

```JS
import withNuxt from './.nuxt/eslint.config.mjs';
import globals from 'globals';

export default withNuxt({
    rules: {
        'vue/html-self-closing': 'off',
        'nuxt/prefer-import-meta': 'off',
    },
    languageOptions: {
        globals: { ...Object.entries(globals.browser).reduce((acc, [key, value]) => ({ ...acc, [key.trim()]: value }), {}), ...Object.entries(globals.node).reduce((acc, [key, value]) => ({ ...acc, [key.trim()]: value }), {}) },
    },
});
```

------

Just using what is recommended in the [Eslint doc](https://arc.net/l/quote/furmzxef) gives an error:

```JS
import globals from "globals";
export default [
    {
        languageOptions: {
            globals: {
                ...globals.browser
            }
        }
    }
];
```

```
[Error - 7:57:16 AM] An unexpected error occurred:
[Error - 7:57:16 AM] Error: Key "languageOptions": Key "globals": Global "AudioWorkletGlobalScope " has leading or trailing whitespace.
    at ObjectSchema.validate (/Users/nicol/_Dev/apps/vet-app/front-end/node_modules/@humanwhocodes/object-schema/src/object-schema.js:287:23)
    at /Users/nicol/_Dev/apps/vet-app/front-end/node_modules/@humanwhocodes/object-schema/src/object-schema.js:239:18
    at Array.reduce (<anonymous>)
    at ObjectSchema.merge (/Users/nicol/_Dev/apps/vet-app/front-end/node_modules/@humanwhocodes/object-schema/src/object-schema.js:237:24)
    at /Users/nicol/_Dev/apps/vet-app/front-end/node_modules/@humanwhocodes/config-array/api.js:935:42
    at Array.reduce (<anonymous>)
    at FlatConfigArray.getConfig (/Users/nicol/_Dev/apps/vet-app/front-end/node_modules/@humanwhocodes/config-array/api.js:934:39)
    at FlatESLint.calculateConfigForFile (/Users/nicol/_Dev/apps/vet-app/front-end/node_modules/eslint/lib/eslint/flat-eslint.js:1091:24)
    at async FlatESLint.isPathIgnored (/Users/nicol/_Dev/apps/vet-app/front-end/node_modules/eslint/lib/eslint/flat-eslint.js:1113:24)
    at async FlatESLint.lintText (/Users/nicol/_Dev/apps/vet-app/front-end/node_modules/eslint/lib/eslint/flat-eslint.js:952:33)
```

**Comment by davidurco** [comment]
Thanks, that works. I tried spreading `...gobals.browser` but got the same error as you. Do you think this should be integrated into nuxt eslint?

**Comment by jeannen** [comment]
Definitely, I think the point of the plugin is to have eslint "ready to use" for Nuxt!

I know we can suggest code change on Github but I have no idea how to do that, if anyone wants to add it, feel free to use the code I posted above!

**Comment by davidurco** [comment]
@jeannen I doubt we want to spread the whole `globals` object, as it consists of a lot of specific globals like for example `jQuery`. I think `node` and `browser` are the ones we are interested in.

**Comment by davidurco** [comment]
@jeannen Sorry, just realised your snipper is only spreading browser and node. Sorry ✌️ .
