### ISSUE TITLE
Eslint doesn't work after adding @nuxt/eslint module

### ISSUE THREAD

**Issue by KonradDRAST** [nuxt/eslint#383]
### Environment

------------------------------
- Operating System: Windows_NT
- Node Version:     v20.10.0
- Nuxt Version:     3.11.2
- CLI Version:      3.11.1
- Nitro Version:    2.9.6
- Package Manager:  yarn@1.22.19
- Builder:          -
- User Config:      app, build, css, devtools, modules
- Runtime Modules:  @nuxt/eslint@0.3.0-beta.9, @nuxtjs/tailwindcss@6.11.4, shadcn-nuxt@0.10.2
- Build Modules:    -
------------------------------

### Package

@nuxt/eslint

### Reproduction

Nuxt 3 project with Typescript. Eslint module added to project according to docs.

### Describe the bug

The moment I open any `.vue` file there is an error in the output console:

[Info  - 3:35:06 PM] ESLint server is starting.
[Info  - 3:35:07 PM] ESLint server running in node v18.18.2
[Info  - 3:35:07 PM] ESLint server is running.
[Info  - 3:35:20 PM] ESLint library loaded from: D:\Web\wonline-demo\packages\frontend-admin\node_modules\eslint\lib\api.js
[Error - 3:35:20 PM] An unexpected error occurred:
[Error - 3:35:20 PM] Error: Could not find config file.
    at locateConfigFileToUse (D:\Web\wonline-demo\packages\frontend-admin\node_modules\eslint\lib\eslint\flat-eslint.js:336:21)
    at async calculateConfigArray (D:\Web\wonline-demo\packages\frontend-admin\node_modules\eslint\lib\eslint\flat-eslint.js:371:49)
    at async FlatESLint.lintText (D:\Web\wonline-demo\packages\frontend-admin\node_modules\eslint\lib\eslint\flat-eslint.js:940:25)
    at async c:\Users\konde\.vscode\extensions\dbaeumer.vscode-eslint-3.0.5\server\out\eslintServer.js:1:26928
    at async M (c:\Users\konde\.vscode\extensions\dbaeumer.vscode-eslint-3.0.5\server\out\eslintServer.js:1:19754)
    at async c:\Users\konde\.vscode\extensions\dbaeumer.vscode-eslint-3.0.5\server\out\eslintServer.js:1:233425
    at async c:\Users\konde\.vscode\extensions\dbaeumer.vscode-eslint-3.0.5\server\out\eslintServer.js:1:63833

Eslint doesn't work.

### Additional context

I've removed `.lock` file, `node_modules` directory, and reinstalled dependencies. No luck.

**Comment by KonradDRAST** [comment]
OMG. My fault. spelling mistake in `eslint.config.mjs`  (was esilnt). Closing.
