### ISSUE TITLE
Error while loading rule '@typescript-eslint/no-unused-expressions': Cannot read properties of undefined (reading 'allowShortCircuit')

### ISSUE THREAD

**Issue by naruko-hstk** [nuxt/eslint#518]
### Environment

Working directory: /Users/naruko_hstk/afei                                                                     3:14:20
Nuxt project info: (copied to clipboard)                                                                       3:14:20

------------------------------
- Operating System: Darwin
- Node Version:     v22.11.0
- Nuxt Version:     3.14.159
- CLI Version:      3.15.0
- Nitro Version:    2.10.4
- Package Manager:  npm@10.9.0
- Builder:          -
- User Config:      default
- Runtime Modules:  @nuxt/ui@2.19.2, @nuxt/eslint@0.6.1
- Build Modules:    -
------------------------------

                                                                                                               3:14:20
👉 Report an issue: https://github.com/nuxt/nuxt/issues/new?template=bug-report.yml
👉 Suggest an improvement: https://github.com/nuxt/nuxt/discussions/new
👉 Read documentation: https://nuxt.com

### Package

@nuxt/eslint

### Reproduction

https://github.com/naruko-hstk/afei

### Describe the bug

Here's Log
```
[Error - 上午3:09:11] TypeError: Error while loading rule '@typescript-eslint/no-unused-expressions': Cannot read properties of undefined (reading 'allowShortCircuit')
Occurred while linting /Users/naruko_hstk/afei/app.vue
    at Object.create (/Users/naruko_hstk/afei/node_modules/eslint/lib/rules/no-unused-expressions.js:75:13)
    at create (/Users/naruko_hstk/afei/node_modules/@typescript-eslint/eslint-plugin/dist/rules/no-unused-expressions.js:28:32)
    at Object.create (/Users/naruko_hstk/afei/node_modules/@typescript-eslint/utils/dist/eslint-utils/RuleCreator.js:31:20)
    at createRuleListeners (/Users/naruko_hstk/afei/node_modules/eslint/lib/linter/linter.js:944:21)
    at /Users/naruko_hstk/afei/node_modules/eslint/lib/linter/linter.js:1082:84
    at Array.forEach (<anonymous>)
    at runRules (/Users/naruko_hstk/afei/node_modules/eslint/lib/linter/linter.js:1013:34)
    at #flatVerifyWithoutProcessors (/Users/naruko_hstk/afei/node_modules/eslint/lib/linter/linter.js:1911:31)
    at Linter._verifyWithFlatConfigArrayAndWithoutProcessors (/Users/naruko_hstk/afei/node_modules/eslint/lib/linter/linter.js:1993:49)
    at /Users/naruko_hstk/afei/node_modules/eslint/lib/linter/linter.js:1609:29
```

### Logs

```shell-script
[Error - 上午3:09:11] TypeError: Error while loading rule '@typescript-eslint/no-unused-expressions': Cannot read properties of undefined (reading 'allowShortCircuit')
Occurred while linting /Users/naruko_hstk/afei/app.vue
    at Object.create (/Users/naruko_hstk/afei/node_modules/eslint/lib/rules/no-unused-expressions.js:75:13)
    at create (/Users/naruko_hstk/afei/node_modules/@typescript-eslint/eslint-plugin/dist/rules/no-unused-expressions.js:28:32)
    at Object.create (/Users/naruko_hstk/afei/node_modules/@typescript-eslint/utils/dist/eslint-utils/RuleCreator.js:31:20)
    at createRuleListeners (/Users/naruko_hstk/afei/node_modules/eslint/lib/linter/linter.js:944:21)
    at /Users/naruko_hstk/afei/node_modules/eslint/lib/linter/linter.js:1082:84
    at Array.forEach (<anonymous>)
    at runRules (/Users/naruko_hstk/afei/node_modules/eslint/lib/linter/linter.js:1013:34)
    at #flatVerifyWithoutProcessors (/Users/naruko_hstk/afei/node_modules/eslint/lib/linter/linter.js:1911:31)
    at Linter._verifyWithFlatConfigArrayAndWithoutProcessors (/Users/naruko_hstk/afei/node_modules/eslint/lib/linter/linter.js:1993:49)
    at /Users/naruko_hstk/afei/node_modules/eslint/lib/linter/linter.js:1609:29
```

**Comment by naruko-hstk** [comment]
b.t.w.
Log is from eslint plugin on vscode

**Comment by christophermiles** [comment]
I am having this exact issue.

**Comment by antfu** [comment]
This is an upstream bug of `typescript-eslint` + `eslint@9.15.0`: https://github.com/typescript-eslint/typescript-eslint/issues/10338

Before `typescript-eslint` catch up, the workaround is to lock eslint at `9.14.0`

**Comment by antfu** [comment]
`typescript-eslint@8.15` fixed this: https://github.com/typescript-eslint/typescript-eslint/issues/10338#issuecomment-2483750053

The version of `typescript-eslint` is also bumped in `@nuxt/eslint@0.7.1`
